easypr/urls.py
from zinnia.sitemaps import TagSitemap
from zinnia.sitemaps import EntrySitemap
from zinnia.sitemaps import CategorySitemap
from zinnia.sitemaps import AuthorSitemap


from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^easypr_admin/', include(admin.site.urls)),
    url('^',      include('easypr_ng.urls',      namespace  = "easypr_ng")),
    url('^admin/', include('easypr_admin.urls',   namespace  = "easypr_admin")),
    url('^',      include('easypr_general.urls', namespace  = "general")),
    url(r'^blog/', include('zinnia.urls')),
    url(r'^comments/', include('django_comments.urls'))
]

# sitemaps = {'tags': TagSitemap,
#             'blog': EntrySitemap,
#             'authors': AuthorSitemap,
#             'categories': CategorySitemap,}

# urlpatterns += [
#     'django.contrib.sitemaps.views',
#     url(r'^sitemap.xml$', 'index',
#         {'sitemaps': sitemaps}),
#     url(r'^sitemap-(?P<section>.+)\.xml$', 'sitemap',
#         {'sitemaps': sitemaps})]

easypr_admin/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from easypr_admin import views


# Create your urls here.
urlpatterns  =  [

             
	# url(r'^/admin/$',                         				views.dashboardView,      name='admin-dashboard'),
	url(r'^(?P<section_title>[-\w]+)/$',               views.dashboardView,                name='admin-dashboard'),
	
	url(r'^ajax/ajax-load-page/$',                    views.ajaxLoadDashboard,             name='load-content-page'),
	url(r'^ajax/fetch-single-post/$',                 views.fetchSinglePost,               name='fetch-post'),
	url(r'^ajax/save-changes/$',                      views.updatePost,                    name='update-post'),
	url(r'^process/send-to-media/$',                  views.send_post_to_media,            name='post-to-media'),
	url(r'^process/reject-post/$',                    views.rejectPost,                    name='reject-post'),
	url(r'^process/publish-post/$',                   views.publishPost,                   name='publish-post'),


	# url(r'^about_us/$',                					views.aboutUsView,        name='about_us'),
	# # url(r'^services/$',                                 views.servicesView,       name='services'),
	# url(r'^newsroom/$',                					views.newsroomView,       name='newsroom'),
	# url(r'^contact_us/$',      		   					views.contactView,        name='contact_us'),
	# url(r'^sign_up/$',         		   					views.signUpView,         name='sign_up'),
	# url(r'^login/$',           		   					views.loginView,          name='login'),
	# url(r'^logout/$',          		   					views.logoutView,         name='logout'),
	# url(r'^accounts/posts/$',          	                views.dashboardView,      name='user-dashboard'),
	# url(r'^terms-and-conditions/$',          		    views.TandCView,          name='tandc'),
	# # url(r'^client/feedback/$',                          views.clientFeedback,           name = 'user-feedback'),
	# url(r'^article/create/new/$',      					views.createArticleView,  name='create-article'),
	# url(r'^services/$',                                 TemplateView.as_view(template_name = "yadel/general/services.html"), name='services'),
	# url(r'^thank-you/$',      					        TemplateView.as_view(template_name = "yadel/general/thank-you.html"), name='registration_success'),
	# url(r'^confirm-registration/(?P<code>[-\w]+)/$',    views.confirmEmail, name = 'confirm-email'),
	# # url(r'^news/(?P<pk>[-\d]+)/(?P<news_title>[-\w]+)/url=(?P<url_link>[-\w]+)/$',  views.loadExternalNews, name = 'news-details')

	# url(r'^news/(?P<pk>[-\d]+)/(?P<news_title>[-\w]+)/$',  views.loadExternalNews, name = 'news-details')

	] 
	 # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

easypr_ng/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from easypr_ng import views


urlpatterns  =  [     
	url(r'^$',                       views.indexView,                	     name='index'),
	url(r'^planner/step(?P<step>[-\d]+)/UID=(?P<anon_userID>[-\w\d]+)$',      	    views.strategyPlannerView,   name='strategy-planner'),
	url(r'^planner/$',      	                                        views.strategyPlannerIntroView,          name='strategy-planner-intro'),
	
	url(r'^news/(?P<post_id>[-\d]+)/(?P<title_slug>[-\w]+)/$',  		 views.readnewsView,            name = 'news-details'),
	
	url(r'^newsroom/$',                				                     views.newsRoomView,            name = 'newsroom'),
	url(r'^newsroom/category=(?P<category>[-\w\d]+)$',                	 views.newsRoomCatView,         name = 'newsroom-cat-view'),
	
	url(r'^post-comment/$',                                 	         views.postCommentView,         name = 'post-comment'),
	url(r'^post/comment/reply/$',                	                     views.postCommentReplyView,    name = 'post-reply'),

	url(r'^our-works/$',                				                 views.ourWorksView,            name = 'our-works'),
	url(r'^buy-package/press_material=(?P<press_material>[-\w]+)/package=(?P<package>[-\w]+)/$', views.buy_packageView, name = "buy-package"),
	url(r'^content-upload/preview/ref=(?P<transaction_id>[-\w]+)$',      views.previewPublicationView,  name = "preview-content"),
	url(r'^fetch-media-houses/$',                                        views.ajax_get_media_houses,        name = 'get-media-houses'),
	
	url(r'^fetch-blog-list/$',                                           views.get_blog_list,           name = 'get-blog-list'),
	
	url(r'^payment/ref=(?P<transaction_id>[-\w]+)$',                     views.Payment,                 name = 'payment'),
	
	url(r'^payment/save-details/$',                                      views.savePayInfo,             name = 'save-pay-details'),
	# url(r'^payment/save-details/ref=(?P<transaction_id>[-\w]+)/$',       views.savePayInfo,             name = 'save-pay-details'),
	
	url(r'^content-submission/success/$',                                views.confirmationView,        name = 'confirmation'),

	url(r'^services/(?P<service_category>[-\w]+)/$',         			 views.servicesView,            name = 'service-details'),
	url(r'^bespoke-bundle-plans/$',                                      views.bundlePlanView,          name = 'bundle-plans'),
	url(r'^marketing-bundles/buy/bundle=(?P<pk>[-\w]+)/$',               views.buyBundleView,           name = 'buy-bundle'),
	
	url(r'^(?P<category>[-\w]+)/(?P<item>[-\w]+)/pricing/$',             views.get_startedView,         name = 'get-started'),
	url(r'^(?P<category>[-\w]+)/(?P<item>[-\w]+)/submit-content/$',      views.submitContentView,       name = 'submit-content'),
	url(r'^(?P<category>[-\w]+)/(?P<item>[-\w]+)/submit-request/$',      views.requestServiceView,      name = 'request-service'),

	url(r'^ajax/create-purchase-for-bundle/$',                           views.createBundlePurchase,   name='create_purchase_for_bundle'),
	url(r'^ajax/make-card-payment/$',                                    views.makeCardPayment,        name='make-card-payment'),
	url(r'^ajax/make-card-payment/verify/(?P<txn_ref>[-\w]+)/$',         views.verifyCardPayment,      name='verify-card-payment'),



	# url(r'^(?P<section_title>[-\w]+)/$',      views.dashboardView,       name='admin-dashboard'),
	url(r'^user/(?P<section_title>[-\w]+)$',  views.userDashboard,       name='user-dashboard'),
	url(r'^ajax/ajax-load-page/$',            views.loadUserDashboard,   name='load-content-page'),
	url(r'^ajax/fetch-single-post/$',         views.fetchSinglePost,     name='fetch-post'),
	url(r'^ajax/save-changes/$',              views.updateUserPost,          name='update-post'),
	# url(r'^process/send-to-media/$',          views.send_post_to_media,  name='post-to-media'),
	url(r'^process/reject-post/$',            views.rejectPost,          name='reject-post'),
	url(r'^process/delete-post/(?P<post_pk>[-\w]+)/$',            views.deletePost,      name='delete-post'),
	] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

easypr_admin/models.py
from django.db import models

# Create your models here.

easypr_ng/forms.py
from django import forms
from django.contrib.auth.models import User
from easypr_ng.models import *
from easypr_general.models import *
from easypr_general.models_field_choices import *
# from django.forms import modelform_factory,Select,TextInput,Textarea,CheckboxInput,EmailInput
# from django
# from multiupload.fields import MultiFileField




class ContentUploadForm(forms.ModelForm):
	post_title         =    forms.CharField(max_length = 200, widget=forms.TextInput(attrs=
					        {'class' : 'form-control no-border-radius title bg-white', 'placeholder': 'Enter post title','required':'required', 'maxLength':200}))	
	# platform       			 =    forms.CharField(max_length = 128, widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder': 'Last Name', 'required':'required'}))
	person_to_quote    =    forms.CharField(max_length = 128, widget=forms.TextInput(attrs=
						    {'class' : 'form-control no-border-radius bg-white', 'placeholder': 'Person to quote', 'required':'required'}))
	persons_position   =    forms.CharField(max_length = 128, widget=forms.TextInput(attrs=
							{'class' : 'form-control no-border-radius bg-white', 'placeholder': 'Position', 'required':'required'}))
	# media_houses             =    forms.CharField(max_length = 128, widget=forms.Select(attrs={'class' : 'form-control', 'placeholder': 'Last Name', 'required':'required'}))
	post_body          =    forms.CharField(max_length = 3000, widget=forms.Textarea(attrs=
							{'class' : 'form-control no-border-radius bg-white', 'placeholder': 'Type or copy and paste content here','required':'required','rows':20, 'maxLength':3000}))
	publish_online     =    forms.CharField(max_length = 10, widget=forms.CheckboxInput(attrs={'value' : 'false'}))
	


	class Meta:
		model = Publication
		fields = ('post_title','person_to_quote', 'persons_position','post_body','publish_online',)





class BizInfoForm(forms.ModelForm):
	# business_type      =    forms.ModelChoiceField(queryset = BUSINESS_TYPE, widget=forms.Select(attrs={'class' : 'form-control no-border-radius title bg-white', 'required':'required'}))
	business_type      =    forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius title bg-white', 'required':'required'}))
	company_type       =    forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius title bg-white', 'required':'required'}))
	is_pr_agent        =    forms.CharField(max_length = 10, widget=forms.CheckboxInput(attrs={'value' : 'false'}))
	size_of_pr_team    =    forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius title bg-white','required':'required'}))

	class Meta:
		model = PRStrategy
		fields  =  ('business_type','company_type','is_pr_agent','size_of_pr_team')



class TargetAudienceForm(forms.ModelForm):
	target_audience 	=       forms.CharField(max_length = 1000, widget=forms.Textarea(attrs=
							{'class' : 'form-control no-border-radius bg-white', 'required':'required','rows':20}))
	pr_goals        	=       	forms.CharField(max_length = 1000, widget=forms.Textarea(attrs=
									{'class' : 'form-control no-border-radius bg-white', 'required':'required','rows':20}))
	frequency_of_pr 	=       	forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius title bg-white', 'required':'required'}))
	target_audience_location  =      forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius title bg-white', 'required':'required'}))
   



	class Meta:
		model = PRStrategy
		fields = ('target_audience','pr_goals','frequency_of_pr','target_audience_location',)



class ServiceRequestForm(forms.ModelForm):
	# service_type      =    forms.CharField(max_length = 100, widget=forms.Select(choices = SERVICE_TYPE, attrs={'class' : 'form-control no-border-radius border-thick', 'required':'required'}))
	# sector            =    forms.CharField(max_length = 100, widget=forms.Select(choices = ECONOMY_SECTOR, attrs={'class' : 'form-control no-border-radius border-thick', 'required':'required'}))
	# brief_description   =    forms.CharField(max_length = 450, required=False, widget=forms.Textarea(attrs={'class' : 'form-control no-border-radius bg-white border-thick','rows':5,'placeholder':"Briefly describe the service you want."}))
	# brief_description   =    forms.CharField(max_length = 450, required=False, widget=forms.Textarea(attrs={'class' : 'form-control no-border-radius bg-white border-thick','rows':5,'placeholder':"Briefly describe the service you want."}))
	# sector            =    forms.CharField(max_length = 100, widget=forms.Select(choices = MEDIA_PLATFORM, attrs={'class' : 'form-control no-border-radius border-thick', 'required':'required'}))
	# time_service_needed  =    forms.DateField(widget=forms.DateInput(attrs={'class' : 'form-control no-border-radius border-thick', 'required':'required'}))
	# preferred_call_time  =    forms.CharField(max_length = 100, widget=forms.Select(attrs={'class' : 'form-control no-border-radius border-thick', 'required':'required'}))
	# allow_call           =    forms.CharField(max_length = 100, widget=forms.CheckboxInput(attrs={'class' : 'form-control no-border-radius border-thick', 'required':'required'}))
	contact_person     	 =    forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius bg-white border-thick', 'required':'required'}))
	contact_email     	 =    forms.CharField(max_length = 200, widget=forms.EmailInput(attrs={'class' : 'form-control no-border-radius bg-white border-thick', 'required':'required'}))
	phone_number     	 =    forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius bg-white border-thick', 'required':'required'}))
	# ticket_number     	 =    forms.CharField(max_length = 14, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius bg-white border-thick', 'required':'required'}))


	# def __init__(self, *args, **kwargs):
	# 	super(ServiceRequestForm, self).__init__(*args, **kwargs)
	# 	self.fields['brief_description'].required = self.instance.pk is None



	class Meta:
		model  = ServiceRequest
		fields = ('contact_person','contact_email','phone_number')
		# fields = ('brief_description', 'contact_person','contact_email','phone_number')

easypr_admin/templates/snippets/accounts-manager.html
<section>
	<div class="container">
		<div class="row">
			<h4> {{ section_title }} </h4>
		</div>
	</div>
</section>

easypr_admin/templates/snippets/affiliate-manager.html
<section>
	<div class="container">
		<div class="row">
			<h4> {{ section_title }} </h4>
		</div>
	</div>
</section>

easypr_admin/templates/snippets/ajax-content.html
{% load base_custom_filters %}
{% load staticfiles %}

{% if content_type == "submissions" %}
	{% for item in content_list %}
		<div class="row post_strip text-dark {% if forloop.counter|is_even %} bg-even {% endif %}">
			<div class="col-md-2">
				<img class="thumbnail" src="{% if item.featured_image %}{{ item.featured_image }}{% else %}{% static 'easypr/images/icons/no-image-sm.png' %} {% endif %}" alt="easyPR Nigeria">
			</div>
			<div class="col-md-8">

				<strong class="text-primary"><a href="#" post_id = "{{ item.pk }}" {% if item.status.lower == "new" %} class="preview-post" {% endif %}>{{ item.post_title|title|truncatewords:12 }}</strong><br>
				<small class="text-justify">{{ item.post_body|truncatewords:35 }}</small><br>
				<div class="bg-royal text-white" style="padding:3px;"><small>Selected Media:</small> <strong>{{ item.get_media_houses|title|truncatewords:12 }}</strong></div><br>
			</div>
			<div class="col-md-2 text-center" style="padding-top: 50px;">
				{% if item.status.lower == "new" %}
					<p><a href="#" post_id = "{{ item.pk }}" title="preview" class="preview-post"><i class="fa fa-search" ></i></a>
					{% if request.user.is_admin or request.user.is_superuser %}
						<a href="#" post_id = "{{ item.pk }}" title="Send to media house" class="send-to-media"><i class="fa fa-newspaper-o space-left"></i></a>
						<a href="#" post_id = "{{ item.pk }}" title="Send to Ext Editor" class="send-to-ext-editor"><i class="fa fa-external-link space-left" ></i></a>
					{% endif %}
					<a href="#" post_id = "{{ item.pk }}" class="text-danger reject-post" title="Reject"><i class="fa fa-trash space-left"></i></a></p>
				{% elif item.status.lower == "sent_to_external_editor" or item.status.lower == "processing" and request.user.is_superuser %}
					<a href="#" post_id = "{{ item.pk }}" class="publish" title="publish post"><i class="fa fa-clipboard space-left" ></i></a><br>
				{% elif item.status.lower == "published" %}
					<a href="{% url 'easypr_ng:news-details' item.pk item.title_slug %}" class="btn btn-sm btn-success" title="view post in newsroom">View post</a>
				{% elif item.status.lower == "pending" %}
					<a href="{% url 'easypr_ng:preview-content' item.transaction_id %}" class="text-success" title="continue editing"><i class="fa fa-pencil space-left" ></i></a>
					<a href="{% url 'easypr_ng:delete-post' item.pk %}" class="text-danger delete_post" title="delete post"><i class="fa fa-trash space-left" ></i></a>
				{% endif %}
			</div>
		</div>
	{% empty %}
		<p>No post found.</p>
	{% endfor %}
{% elif content_type == "users" %}
	{% for user in content_list %}
		{{ user }}
	{% empty %}
		<p>No User found.</p>
	{% endfor %}
{% endif %}

easypr_admin/templates/snippets/analytics.html
<section>
	<div class="container">
		<div class="row">
			<h4> {{ section_title }} </h4>
		</div>
	</div>
</section>

easypr_admin/templates/snippets/blog-manager.html
<section>
	<div class="container">
		<div class="row">
			<h4> {{ section_title }} </h4>
		</div>
	</div>
</section>

easypr_admin/templates/snippets/content-manager.html
<section>
	<div class="container">
		<div class="row">
			<h4> {{ section_title }} </h4>
		</div>
	</div>
</section>

easypr_admin/templates/snippets/media-contacts-modal.html
{% load humanize %}
{% load staticfiles %}

	<div id="{{ modal_Id }}" class="modal fade">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content no-border-radius">
	      <div class="modal-header bg-warning">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #000000;">
	          <span aria-hidden="true">&times;</span>
	        </button>
	        <h5 class="modal-title">Select Media Contact</h5>
	      </div>
	      <form action="{% url 'easypr_admin:post-to-media' %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="post_id" id="active_post_id">
	      	<div class="modal-body text-center text-black" id="id_media_contacts">
	      		<!-- Ajax populated contact list -->
	      	</div> <!-- modal body ends -->
	        <div class="modal-footer">
				<input type="submit" class="pull-right" id="id_save_changes" value="Send">
				<a href="{{ previous_page }}" data-toggle="modal" data-dismiss = "modal" id="id_discard_changes" class="btn pull-left text-danger">Dismiss</a>
		    </div>
		  </form>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

easypr_admin/templates/snippets/post-media-contacts.html
<table class="table table-stripped" border="1">
	<thead>
		<tr class="bg-royal text-white">
			<th align="center"><input type="checkbox" class="custom-checkbox" id="id_select_all"></th>
			<th>Contact</th>
			<th>Email</th>
			<th>Media House</th>
		</tr>
	</thead>
		<tbody>
		{% for contact in media_contacts %}
			<tr>
				<td><input type="checkbox" class="custom-checkbox media_contact" name="media_contact" value="{{ contact.email }}"></td>
				<td align="left">{{ contact.get_full_name }}</td>
				<td align="left">{{ contact.email }}</td>
				<td align="left">{{ contact.get_media_house|title }}</td>
			</tr>
		{% empty %}
			<tr>
				<td colspan="4"> <p>No media contact found</p></td>
			</tr>
		{% endfor %}
	</tbody>
</table>

easypr_admin/templates/snippets/post-preview.html
{% load humanize %}
{% load staticfiles %}

	<div id="{{ modal_Id }}" class="modal fade">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content no-border-radius">
	      <div class="modal-header bg-warning">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #000000;">
	          <span aria-hidden="true">&times;</span>
	        </button>
	        <h5 class="modal-title">Preview/Edit Post</h5>
	      </div>
	      <div class="modal-body text-center text-black">
	      		<!--  pay option selection form  -->
	      		{% if request.user.is_staff or request.user.is_superuser %}
	      			<form action="{% url 'easypr_admin:update-post' %}" method="post">
	      		{% else %}
	      			<form action="{% url 'easypr_ng:update-post' %}" method="post">
	      		{% endif %}
    				{% csrf_token %}
    				<input type="hidden" id="is_edited" name="is_changed">
					<input type="text" class="form-control title" name="post_title" id ="id_post_title" value="{{ post.title }}" />
					<input type="hidden" name="post_id" id = "id_post_id" />
					<br>
					<textarea name = "post_body" class="form-control text-dark" id="id_post_body" value="{{ post.post_body }}" rows="17"></textarea>
				
			      	</div> <!-- modal body ends -->

			        <div class="modal-footer">
						<input type="submit" class="pull-right" id="id_save_changes" value="Save Changes">
						<a href="{{ previous_page }}" data-toggle="modal" data-dismiss = "modal" id="id_discard_changes" class="btn pull-left text-danger">Discard Changes</a>
				    </div>
				</form>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

easypr_admin/templates/snippets/publish_post.html
{% load humanize %}
{% load staticfiles %}

	<div id="{{ modal_Id }}" class="modal fade">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content no-border-radius">
	      <div class="modal-header bg-warning">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #000000;">
	          <span aria-hidden="true">&times;</span>
	        </button>
	        <h5 class="modal-title">Publish Post</h5>
	      </div>
	      <form action="{% url 'easypr_admin:publish-post' %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="post_id" id="publish_post_id">
	      	<div class="modal-body text-center text-black" id="post_urls">
	      		<p class="pull-left text-dark"><strong>Enter the links to the post on media published. </strong><br><small>Copy and paste the link(s) in the field(s) below</small></p>
	      		<br>
	      		<input type="text" name="post_url[]" class="form-control"  placeholder="Enter media url. eg. http://vanguardngr.com/new-topic-here" required/><br/>
	      		<span id = "id_post_urls"></span>
	      		<br/>
	      		<span class="text-success pull-right"  style="cursor: pointer;" id = "add_url_field"> add more field</span>
	      	</div> <!-- modal body ends -->
	        <div class="modal-footer">
				<input type="submit" class="pull-right btn-success" id="id_save_changes" value="Publish">
				<a href="{{ previous_page }}" data-toggle="modal" data-dismiss = "modal" id="id_discard_changes" class="btn pull-left text-danger"><strong>Cancel</strong></a>
		    </div>
		  </form>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

easypr_admin/templates/snippets/rejection_reason.html
{% load humanize %}
{% load staticfiles %}

	<div id="{{ modal_Id }}" class="modal fade">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content no-border-radius">
	      <div class="modal-header bg-warning">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #000000;">
	          <span aria-hidden="true">&times;</span>
	        </button>
	        <h5 class="modal-title">Enter Reason For Rejection</h5>
	      </div>
	      <form action="{% url 'easypr_admin:reject-post' %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="post_id" id="reject_post_id">
	      	<div class="modal-body text-center text-black" id="id_media_contacts">
	      		<textarea class="form-control" rows="8" id="id_reason" maxlength="300" name="rejection_reason"> </textarea>
	      	</div> <!-- modal body ends -->
	        <div class="modal-footer">
				<input type="submit" class="pull-right btn-danger" id="id_save_changes" value="Reject">
				<a href="{{ previous_page }}" data-toggle="modal" data-dismiss = "modal" id="id_discard_changes" class="btn pull-left text-success"><strong>Cancel</strong></a>
		    </div>
		  </form>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

easypr_admin/templates/snippets/submissions.html
{% load base_custom_filters %}
{% load staticfiles %}

<script>
	$(".default").addClass('active');
</script>
				
{% for item in post_list %}
	<div class="row post_strip text-dark {% if forloop.counter|is_even %} bg-even {% endif %}">
		<div class="col-md-2">
			<img class="thumbnail" src="{% if item.featured_image %}{{ item.featured_image }}{% else %}{% static 'easypr/images/icons/no-image-sm.png' %} {% endif %}" alt="easyPR Nigeria">
		</div>
		<div class="col-md-8">

			<strong class="text-primary"><a href="#" post_id = "{{ item.pk }}" {% if item.status.lower == "new" %} class="preview-post" {% endif %}>{{ item.post_title|title }}</strong><br>
			<small class="text-justify">{{ item.post_body|truncatewords:35 }}</small><br>
			<div class="bg-royal text-white" style="padding:3px;"><small>Selected Media:</small> <strong>{{ item.get_media_houses|title }}</strong></div><br>
		</div>
		<div class="col-md-2 text-center" style="padding-top: 50px;">
			{% if item.status.lower == "new" %}
				<p><a href="#" post_id = "{{ item.pk }}" title="preview" class="preview-post"><i class="fa fa-search" ></i></a>
					
				<a href="#" post_id = "{{ item.pk }}" title="Send to media house" class="send-to-media"><i class="fa fa-newspaper-o space-left"></i></a>
				
				<a href="#" post_id = "{{ item.pk }}" title="Send to Ext Editor" class="send-to-ext-editor"><i class="fa fa-external-link space-left" ></i></a>
				
				<a href="#" post_id = "{{ item.pk }}" class="text-danger reject-post" title="Reject"><i class="fa fa-trash space-left"></i></a></p>
			{% elif item.status.lower == "sent_to_external_editor" or item.status.lower == "processing" %}
				<a href="#" post_id = "{{ item.pk }}" class="publish" title="publish post"><i class="fa fa-clipboard space-left" ></i></a><br>
			{% endif %}
		</div>
	</div>
{% empty %}
	<p>No post found .</p>
{% endfor %}

easypr_admin/templates/snippets/user-manager.html
<script>
	$(".default").addClass('active');
</script>
{% for user in content_list %}
	<p> {{ user }} </p>
{% empty %}
	<p>No user found</p>
{% endfor %}
							