easypr/urls.py
from zinnia.sitemaps import TagSitemap
from zinnia.sitemaps import EntrySitemap
from zinnia.sitemaps import CategorySitemap
from zinnia.sitemaps import AuthorSitemap


from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^easypr_admin/', include(admin.site.urls)),
    url('^',      include('easypr_ng.urls',      namespace  = "easypr_ng")),
    url('^admin/', include('easypr_admin.urls',   namespace  = "easypr_admin")),
    url('^',      include('easypr_general.urls', namespace  = "general")),
    url(r'^blog/', include('zinnia.urls')),
    url(r'^comments/', include('django_comments.urls'))
]

# sitemaps = {'tags': TagSitemap,
#             'blog': EntrySitemap,
#             'authors': AuthorSitemap,
#             'categories': CategorySitemap,}

# urlpatterns += [
#     'django.contrib.sitemaps.views',
#     url(r'^sitemap.xml$', 'index',
#         {'sitemaps': sitemaps}),
#     url(r'^sitemap-(?P<section>.+)\.xml$', 'sitemap',
#         {'sitemaps': sitemaps})]

easypr_general/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from easypr_general import views


# Create your urls here.
urlpatterns  =  [

             
	url(r'^$',                         				   views.indexView,                 name='homepage'),
	url(r'^who-we-are/$',                			   views.aboutUsView,               name='about-us'),
	url(r'^contact_us/$',      		   				   views.contactView,               name='contact-us'),
	url(r'^user/sign-up/$',         		   	       views.createUserAccount,         name='sign-up'),
	
	# url(r'^user/(?P<section_title>[-\w]+)$',           views.userDashboard,             name='user-dashboard'),
	# url(r'^user/(?P<section_title>[-\w]+)$',           views.userDashboard,             name='admin-dashboard'),
	
	url(r'^login/$',           		   				   views.loginView,          		name='login'),
	url(r'^logout/$',          		   				   views.logOutView,         		name='logout'),
	url(r'^careers/$',          	                   views.careersView,        		name='careers'),
	# url(r'^blog/$',          	                       views.careersView,            name='blog'),
	url(r'^subscribe/$',          	                   views.mailListView,           name='mailing-list-subscription'),
	url(r'^forgot-password/$', 						   views.forgotPasswordView,     name='forgot-password'),
    url(r'^reset-password/token=(?P<code>[-\w]+)/$',   views.resetPasswordView,  	 name='reset-password'),
	url(r'^confirm-registration/(?P<code>[-\w]+)/$',   views.confirmEmail, 			 name = 'confirm-email'),
	url(r'^thank-you/$',      					       TemplateView.as_view(template_name = "easypr_general/thank-you.html"), name='registration_success'),
	url(r'^frequently-asked-questions/$',          	   TemplateView.as_view(template_name = "easypr_general/faq.html"),  name='faq'),
	url(r'^how-it-works/$',          	               TemplateView.as_view(template_name = "easypr_general/how-it-works.html"),  name='how-it-works'),
	url(r'^terms-and-conditions/$',          	       TemplateView.as_view(template_name = "easypr_general/terms-and-conditions.html"),  name='terms-and-conditions'),

] 

# if DEBUG:
#     urlpatterns += [
#         url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
#             {'document_root': MEDIA_ROOT}),

#         url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#             {'document_root': STATIC_ROOT}),
# ]

easypr_ng/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from easypr_ng import views


urlpatterns  =  [     
	url(r'^$',                       views.indexView,                	     name='index'),
	url(r'^planner/step(?P<step>[-\d]+)/UID=(?P<anon_userID>[-\w\d]+)$',      	    views.strategyPlannerView,   name='strategy-planner'),
	url(r'^planner/$',      	                                        views.strategyPlannerIntroView,          name='strategy-planner-intro'),
	
	url(r'^news/(?P<post_id>[-\d]+)/(?P<title_slug>[-\w]+)/$',  		 views.readnewsView,            name = 'news-details'),
	
	url(r'^newsroom/$',                				                     views.newsRoomView,            name = 'newsroom'),
	url(r'^newsroom/category=(?P<category>[-\w\d]+)$',                	 views.newsRoomCatView,         name = 'newsroom-cat-view'),
	
	url(r'^post-comment/$',                                 	         views.postCommentView,         name = 'post-comment'),
	url(r'^post/comment/reply/$',                	                     views.postCommentReplyView,    name = 'post-reply'),

	url(r'^our-works/$',                				                 views.ourWorksView,            name = 'our-works'),
	url(r'^buy-package/press_material=(?P<press_material>[-\w]+)/package=(?P<package>[-\w]+)/$', views.buy_packageView, name = "buy-package"),
	url(r'^content-upload/preview/ref=(?P<transaction_id>[-\w]+)$',      views.previewPublicationView,  name = "preview-content"),
	url(r'^fetch-media-houses/$',                                        views.ajax_get_media_houses,        name = 'get-media-houses'),
	
	url(r'^fetch-blog-list/$',                                           views.get_blog_list,           name = 'get-blog-list'),
	
	url(r'^payment/ref=(?P<transaction_id>[-\w]+)$',                     views.Payment,                 name = 'payment'),
	
	url(r'^payment/save-details/$',                                      views.savePayInfo,             name = 'save-pay-details'),
	# url(r'^payment/save-details/ref=(?P<transaction_id>[-\w]+)/$',       views.savePayInfo,             name = 'save-pay-details'),
	
	url(r'^content-submission/success/$',                                views.confirmationView,        name = 'confirmation'),

	url(r'^services/(?P<service_category>[-\w]+)/$',         			 views.servicesView,            name = 'service-details'),
	url(r'^bespoke-bundle-plans/$',                                      views.bundlePlanView,          name = 'bundle-plans'),
	url(r'^marketing-bundles/buy/bundle=(?P<pk>[-\w]+)/$',               views.buyBundleView,           name = 'buy-bundle'),
	
	url(r'^(?P<category>[-\w]+)/(?P<item>[-\w]+)/pricing/$',             views.get_startedView,         name = 'get-started'),
	url(r'^(?P<category>[-\w]+)/(?P<item>[-\w]+)/submit-content/$',      views.submitContentView,       name = 'submit-content'),
	url(r'^(?P<category>[-\w]+)/(?P<item>[-\w]+)/submit-request/$',      views.requestServiceView,      name = 'request-service'),

	url(r'^ajax/create-purchase-for-bundle/$',                           views.createBundlePurchase,   name='create_purchase_for_bundle'),
	url(r'^ajax/make-card-payment/$',                                    views.makeCardPayment,        name='make-card-payment'),
	url(r'^ajax/make-card-payment/verify/(?P<txn_ref>[-\w]+)/$',         views.verifyCardPayment,      name='verify-card-payment'),



	# url(r'^(?P<section_title>[-\w]+)/$',      views.dashboardView,       name='admin-dashboard'),
	url(r'^user/(?P<section_title>[-\w]+)$',  views.userDashboard,       name='user-dashboard'),
	url(r'^ajax/ajax-load-page/$',            views.loadUserDashboard,   name='load-content-page'),
	url(r'^ajax/fetch-single-post/$',         views.fetchSinglePost,     name='fetch-post'),
	url(r'^ajax/save-changes/$',              views.updateUserPost,          name='update-post'),
	# url(r'^process/send-to-media/$',          views.send_post_to_media,  name='post-to-media'),
	url(r'^process/reject-post/$',            views.rejectPost,          name='reject-post'),
	url(r'^process/delete-post/(?P<post_pk>[-\w]+)/$',            views.deletePost,      name='delete-post'),
	] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

easypr_general/views.py
# easypr_general.views.py

from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.db.models import F
from django.contrib import messages
from easypr_general.models import UserAccount, Address, LatestNews, ClientFeedback, PwResetRecord, ServiceCategory, MailingList
from easypr_general.forms import  UserRegistrationForm,LoginForm, MailListForm  #LoginForm, UserAccountForm,PublicationForm,DocumentUploadForm
from easypr_general.custom_functions import transaction_ref, get_random_code, paginate_list, easypr_send_mail
from django.contrib.sites.shortcuts import get_current_site



def current_site(request):
    return get_current_site(request).domain


def  indexView(request):
     return HttpResponse(current_site(request))
    

def  createUserAccount(request):
    template = 'easypr_general/sign-up.html'
    form = UserRegistrationForm()
    context = {}
    if  request.method            ==     "POST":
        rp = request.POST
        address                    =     Address.objects.create(address="dummy address")
        reg_code                   =     get_random_code(35)
        user_account_form          =     UserRegistrationForm(data = request.POST)
        if User.objects.filter(email = rp['email']).exists():
            msg  =   "Sorry,  %s  is already registered on this site." %(rp['email'])
            messages.info(request, msg)
            return redirect(request.META['HTTP_REFERER'])
        else:
            if user_account_form.is_valid:
                user = User.objects.create(username = rp['email'], email = rp['email'].lower(),first_name = rp['first_name'], last_name = rp['last_name'])
                user.set_password(rp['password']) 
                user.save()
                UserAccount.objects.create(user = user, registration_code = reg_code, address = address)
                confirmation_link = "http://" + current_site(request) + "/confirm-registration/" + reg_code

                subject = "Confirm your registration."
                mail_context = {'confirmation_link':confirmation_link}
               
                easypr_send_mail(request, recipient = user.first_name, useremail= user.email, text="emails/registration-confirmation.html",subject=subject, context = mail_context)
                context['user_is_created']  =    True
                context['email']            =    rp['email']
                if request.POST.has_key('redirect_to'):
                    messages.info(request, "Your Account has been created succesfully. Complete your registration with confirmation link sent to your email.")
                    return redirect(reverse(request.POST['redirect_to']))
                else:
                    return redirect(reverse('general:registration_success'))
            else:
                return redirect(request.META['HTTP_REFERER'])
    return render(request, template, {})
   
    
def confirmEmail(request,code):
    user_to_confirm = UserAccount.objects.filter(registration_code = code, is_confirmed = False) # try get_object_or_404
    if user_to_confirm.exists():
        user_to_confirm.update(is_confirmed = True)
        messages.success(request, "Thank You!. Your email address has been confirmed. Kindly log in below")
    else:
        pass
    return redirect(reverse('general:login'))


def  loginView(request):
    form = LoginForm()
    context = {}
    username = ""
    context['loginform']  =  form
    if request.method   ==  'POST':
        loginForm       =    LoginForm(data = request.POST)
        if loginForm.is_valid():
            email           =     request.POST.get('email').strip()
            password        =     request.POST.get('password').strip()
            user_account    =     User.objects.filter(email = email)
            if user_account.exists():
                username = user_account[0].username
            auth_user       =     authenticate(username = username, password = password)
            if auth_user is not None:
                user  =  auth_user
                if user.is_active:
                    try:
                        if not user.useraccount.is_confirmed:
                            messages.info(request, "This account has not been activated, click on the link sent to your email to activate your account.") # or request another confirmation link here.")
                            return render(request, 'easypr_general/confirm-email.html', {})
                    except:
                        pass
                    login(request, user) # log user in
                    # #check login source page
                    if request.POST.has_key('next') and not request.POST['next'] == "":
                        next  =   request.POST.get('next')
                        return redirect(next) # return to the called page
                    if user.is_staff or user.is_superuser:
                        return redirect(reverse('easypr_admin:admin-dashboard', kwargs={'section_title':"submissions"}))
                    else:
                        if request.POST.has_key('redirect_to'):
                            return redirect(reverse(request.POST['redirect_to']))
                        else:
                            return redirect('/')
                            # return redirect(reverse('easypr_ng:user-dashboard', kwargs={'section_title':'newsroom'}))
                else:
                    messages.warning(request, 'This account is inactive, send a mail to activate@easypr.ng to request an activation link.')
                    return render(request,  'easypr_general/login.html', context)
            else:
                context['not_found']   =  True
                messages.error(request, "No user matching this email and password found.")
                return render(request,  'easypr_general/login.html', context)
        else:
            context['invalid_form']  =     True
            context['loginform']     =     LoginForm(data = request.POST)
            return render(request,  'easypr_general/login.html', context)
    else:
        return render(request,  'easypr_general/login.html', context)
    return render(request, 'easypr_general/login.html', {'form':form})



def forgotPasswordView(request, **kwargs):
    code = get_random_code(45)
    message = ""
    reset_status = bool
    if request.method == "POST":
        useremail = request.POST['useremail']
        user = User.objects.filter(email = useremail) #check if user exists
        if user.exists():
            try:
                # fetch password reset link record, get_or_create ensures only one active link is available at any time per user
                reset_request,reset_status = PwResetRecord.objects.get_or_create(user = user[0])
                reset_request.reset_code = code
                reset_request.expired = False
                reset_request.save()
            except:
                messages.warning(request, "A password reset link has already been sent to " + user[0].email)
                return render(request, 'easypr_general/reset-password.html', {'search_user':True, 'reset_pw':False, 'link_sent':True, 'email':useremail,})
            reset_link  =   "http://" + current_site(request) + "/reset-password/token=" + code
        
            subject = "Password Reset Link"
            mail_context = {'reset_link':reset_link}
            easypr_send_mail(request, recipient = user[0].first_name, useremail= user[0].email, text="emails/password-reset.html",subject=subject, context = mail_context)
            
            messages.success(request, "We have sent a password reset link to " + useremail + ". You should make use of this link within one hour.")
            return render(request, 'easypr_general/reset-password.html', {'search_user':True, 'reset_pw':False, 'link_sent':True})
        else:
            messages.warning(request, "Sorry! the email address you entered did not fetch any record.")
            return render(request, 'easypr_general/reset-password.html', {'search_user':True, 'reset_pw':False, 'email':useremail,'link_sent':False})
    return render(request, 'easypr_general/reset-password.html', {'search_user':True, 'reset_pw':False})


def resetPasswordView(request, **kwargs):
    code = kwargs['code']
    reset_request = PwResetRecord.objects.filter(reset_code = code, expired=False)
    if reset_request.exists():
        user = reset_request[0].user
        if request.method =="POST":
            rp = request.POST
            if rp['password']  != rp['re-password']:
                messages.warning(request, "The passwords you entered did not match, Please check and try again")
                return redirect(request.META['HTTP_REFERER'])
            user.set_password(rp['password'])
            reset_request.update(expired=True)
            user.save()

            # send email to user
            subject = "Password Reset successful"
            easypr_send_mail(request, recipient = user.first_name, useremail= user.email, text="emails/password-reset-success.html", subject=subject, context = {})
            
            messages.success(request, "Your password reset was successful. Login to continue")
            return redirect(reverse('general:login'))
        else:
            return render(request, 'easypr_general/reset-password.html', {'search_user':False, 'reset_pw':True,'reset_code':code})
    else:
        messages.error(request,"Sorry, this password reset link is invalid. You can request another one below.")
        return render(request, 'easypr_general/reset-password.html', {'search_user':True, 'reset_pw':False})

easypr_general/templates/easypr_general/coming-soon.html
{% extends 'easypr_general/base.html' %}
{% load staticfiles %}
{% block title %}page coming soon{% endblock title %}
{% block inner_content %}
	<section id="main-container" class="main-container">
		<div class="container">
			<div class="row">
				<div class="error-page text-center">
					<!-- <div class="error-code">
						<h2><strong>Page coming Soon</strong></h2>
					</div> -->
					<div class="error-message text-center">
						<img class="img-responsive" src="{% static 'easypr/images/features/coming_soon.png' %}" alt="easypr-services">
						<h3>Yipeee! Thank you for checking</h3>
					</div>
					<div class="error-body">
						<br>
						<a href="/" class="btn btn-primary">Back to Home Page</a>
					</div>
				</div>
			</div><!-- Content row -->
		</div><!-- Conatiner end -->
	</section><!-- Main container end -->
{% endblock inner_content %}

easypr_general/templates/easypr_general/confirm-email.html
{% extends 'easypr_general/base.html' %}
{% load staticfiles %}

{% block title %}Success{% endblock title %}
{% block inner_content %}
	
	<header id="head" class="secondary"></header>
	<!-- container -->
	<div class="container">
		<div class="row">
			<article class="col-xs-12 maincontent">
				<h1> Sorry! </h1>
				{% for msg in messages %}
					<p> {{ msg }} </p>
				{% endfor %}
			</article>
		</div>
	</div>	<!-- /container -->
{% endblock inner_content %}

easypr_general/templates/easypr_general/index.html
{% extends 'easypr_general/base.html' %}
{% load staticfiles %}
{% block title %}PR,Content Distribution, Marketing, Advertising for Africa{% endblock %}

{% block bouquets %}
	<section id="main-container" class="main-container">
		<div class="container">
			<div class="row text-center text-white">
				<h3 class="title-border">
					<span id="packages"></span>
					<span class="title-head" style="padding-bottom: 2px; color:#666666; text-transform: capitalize !important;">Affordable And Targeted Marketing Solutions </span>
					<p>To Help Build Your Brand</p>
					<!-- <p style="font-size: 25px; padding-top:7.5px; text-transform:none;">To Help Build Your Brand</p> -->
				</h3>
			</div><!--/ Title row end -->
			<div class="row">
				<div class="col-md-12">
					<!-- left panel -->
					<div class="col-md-3 tiles-cols">
						<div class="feature-tile-lg">
							<a href="{% url 'easypr_ng:bundle-plans' %}">
								<img class="feature-img-lg" src="{% static 'easypr/images/services/service_tiles/Bespoke Marketing Bundles.jpg' %}" alt="marketing bundles"/>
							</a>
						</div>
					</div>
					<!-- center to right pane  -->
					<div class="col-md-9 tiles-cols">
						<div class="col-md-12">
							<div class="col-md-4"> 
								<div class="feature-tile-sm">
									<a href="{% url 'easypr_ng:service-details' 'press-release-distribution' %}">
										<img class="feature-img-sm" src="{% static 'easypr/images/services/service_tiles/Press Distribution.jpg' %}" alt="EasyPR press distribution" />
									</a>
								</div>
							</div>

							<div class="col-md-4"> 
								<div class="feature-tile-sm">
									<a href="{% url 'easypr_ng:service-details' 'advertising' %}">
										<img class="feature-img-sm" src="{% static 'easypr/images/services/service_tiles/Advertising.jpg' %}" alt="image advertising" />
									</a>
								</div>
							</div>

							<div class="col-md-4"> 
								<div class="feature-tile-sm">
									<a href="{% url 'easypr_ng:service-details' 'sme-start-up-toolkit' %}">
										<img class="feature-img-sm" src="{% static 'easypr/images/services/service_tiles/SME Marketing.jpg' %}" alt="SME marketing" />
									</a>
								</div>
							</div>
						</div>

						<div class="col-md-12">
							<div class="col-md-4"> 
								<div class="feature-tile-sm">
									<a href="{% url 'easypr_ng:service-details' 'events-bureau' %}">
										<img class="feature-img-sm" src="{% static 'easypr/images/services/service_tiles/Events.jpg' %}" alt="Events Bureau" />
									</a>
								</div>
							</div>
							<div class="col-md-4"> 
								<div class="feature-tile-sm bg-info">
									<a href="{% url 'easypr_ng:service-details' 'sales-and-marketing' %}">
										<img class="feature-img-sm" src="{% static 'easypr/images/services/service_tiles/Online Sales and Marketing.jpg' %}" alt="image sales and marketing" />
									</a>
								</div>
							</div>
							<div class="col-md-4"> 
								<div class="feature-tile-sm bg-info">
									<a href="{% url 'easypr_ng:service-details' 'content-writing-and-marketing' %}">
										<img class="feature-img-sm" src="{% static 'easypr/images/services/service_tiles/Content Marketing.jpg' %}" alt="image content marketing " />
									</a>
								</div>
							</div>
							
						</div>
						
					</div>
				</div>
				<div class="gap-10"></div>
				<div class="col-md-12 text-center">
					<a href="{% url 'easypr_ng:strategy-planner-intro' %}" class="slider btn btn-secondary" style="font-size:15px; line-height: 15px;">Not Sure? Find The Right Strategy For Your Brand.</a>
				</div>
			</div>
		</div><!-- Conatiner end -->
	</section><!-- Main container end -->
{% endblock bouquets %}

{% block latest-news %}
	{% if recent_posts %}
		<!-- <div class="gap-10"></div> -->
		<section id="news" class="news">
			<div class="container">
				<div class="row text-center">
					<h3 class="title-border">
						<!-- Get Up to Date -->
						<span>Latest News Around The World</span>
					</h3>
				</div><!--/ Title row end -->
				<div class="gap-10"></div>
				<div class="row">
					{% for post in recent_posts %}
						<div class="col-sm-3">
							<div style="border: thin solid #ffffff;border-radius: 0px; margin-top:5px; padding:8px; display:block; position:relative; text-align: left; box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2), 0 2px 4px 0 rgba(0, 0, 0, 0.19);">
								<div class="latest-post">
								{% if post.featured_image %}
									<div class="latest-post-media">
										<a href="{% url 'easypr_ng:news-details' post.pk post.title_slug %}">
											<img class="img-responsive" src="{{ post.featured_image }}" alt="EasyPR Nigeria News">
										</a>
									</div>
								{% endif %}
									<div class="post-body">
										<h4 class="post-title">
											<a href="{% url 'easypr_ng:news-details' post.pk post.title_slug %}">{{ post.post_title|title }}</a>
											<span class="post-item-date">
												<br/> <i class="fa fa-clock-o"></i> <small>{{ post.date_posted|date }}</small>
											</span>
										</h4>
										<div class="post-text">
											<p>{{ post.post_body|truncatewords:35 }}</p>
										</div>
									</div>	
									<a class="learn-more" href="{% url 'easypr_ng:news-details' post.pk post.title_slug %}">
					         			<i class="fa fa-caret-right"></i> Read More
			                  		</a>
								</div><!-- Latest post end -->
							</div>
						</div><!-- 3rd post col end -->
					{% endfor %}
				</div><!--/ Content row end -->
			</div><!--/ Container end -->
		</section><!--/ News end -->
	{% endif %}
{% endblock latest-news %}

easypr_general/templates/easypr_general/product-details.html
{% extends 'easypr_general/base.html' %}
{% load staticfiles %}

{% block title %}how it works{% endblock title %}
{% block inner_content %}
	<p> &nbsp; </p>
	<p> &nbsp; </p>
	<header id="head" class="secondary"></header>
	<div class="container">
		<div class="row">
			<article class="col-xs-12 maincontent">
				<h3> product details  </h3>
			</article>
		</div>
		
	</div>
	<p> &nbsp; </p>
	<p> &nbsp; </p>
{% endblock inner_content %}

easypr_general/templates/easypr_general/reset-password.html
{% extends 'easypr_general/base.html' %}
{% load staticfiles %}

{% block title %}Reset password{% endblock title %}

{% block inner_content %}
<p> &nbsp; </p>
<p> &nbsp; </p>

<div class="container">
	<div class="row">
		<div class="col-md-2">
			&nbsp;
		</div>
		<div class="col-md-8">
			<!--  if messages %}
				 for msg in messages %}
					<h4 class= "text-{{ msg.tags }}">{{ msg }}</h4>
				 endfor %}
			endif %} -->
			<form name="pw-reset-form" method="post" action="{% if search_user %}{% url 'general:forgot-password' %}{% elif reset_pw %}{% url 'general:reset-password' code=reset_code %} {% endif %}">
				{% csrf_token %}
				{% if search_user %}
					{% if email  %}
						<p>
							<p class="text-primary">Enter your email address to request for password reset link</p>
						</p>
						<input class="form-control" value="{{email}}" type = "email" name="useremail" placeholder="Enter your email" required/>
					{% elif link_sent and not email %}
						<p> &nbsp; </p>
					{% else %}
						<p>
							<p class="text-primary">Enter your email address to request for password reset link</p>
						</p>
						<input class="form-control" type = "email" name="useremail" placeholder="Enter your email" required/>
					{% endif %}
					<input class="form-control" type = "hidden" name="action"  value="check_useremail" /><br/>

					{% if not link_sent %}
						<input type="submit" class="btn btn-primary pull-right" value="Send Request" onclick="this.form.submit()" />
					{% endif %}

				{% elif reset_pw %}
					<p>
						<p class="text-primary">RESET PASSWORD</p>
					</p>
					<input class="form-control" type = "password" name="password" id="new_password" placeholder="Enter a new password" required/><br/>
					<input class="form-control" type = "password" name="re-password" id="re_password" placeholder="Re Enter password" required onblur = 'return compare_passwords("new_password","re_password")'/><br/>
					<input type="submit" id="reset_pw" class="btn btn-primary pull-right" value="Reset Password" onclick = 'return compare_passwords("id_password","id_confirm_password")'/>
				{% endif %}
			</form>
		</div>
		<div class="col-md-2">
			&nbsp;
		</div>
	</div>
	<div class="row">
		<div class="col-md-12"></div>
	</div>
</div>

<p> &nbsp; </p>
<p> &nbsp; </p>

{% endblock inner_content %}





{% block scripts %}
{% endblock scripts %}

easypr_general/templates/easypr_general/services-details.html
{% extends 'easypr_general/base.html' %}
{% load staticfiles %}
{% block title %} {{ service.name|title }} Services{% endblock title %}
{% block inner_content %}
	<div id="banner-area" class="banner-area" style="background-image:url({% if service.banner %}{{ MEDIA_URL }}{{ service.banner.url }}{% endif %})">
	<!-- <div id="banner-area" class="banner-area" style="background-image:url({% static 'easypr/images/banner/banner2.jpg' %})"> -->
		<div class="banner-text">
     		<div class="container">
	        	<div class="row">
	        		<div class="col-xs-12">
	        			<div class="banner-heading text-center">
	        				<!-- <h1 class="banner-title title-border-left">{{ service.name|upper }} </h1> -->
	        				<!-- <p class="">{{ service.description|capfirst }}</p> -->
	        			</div>
	        		</div><!-- Col end -->
	        	</div><!-- Row end -->
       		</div><!-- Container end -->
    	</div><!-- Banner text end -->
	</div><!-- Banner area end --> 

	<section id="main-container" class="main-container">
		<div class="container">
			<div class="row">
				{% for item in service_list %}
					<div class="col-md-4">
					   <div class="ts-service-box" id="{{ item.name_slug }}">
					      <div class="ts-service-image-wrapper">
					         <img class="img-responsive" src="{% if item.image %}{{ item.image.url }}{% endif %}" alt="{{ item.name }} Image">
					      </div>
					      <div class="ts-service-info">
					      	<div class="ts-service-icon">
				          		<i class="fa fa-{{ item.icon_text }} text-dark"></i>
				          		<h3>{{ item.name }}</h3>
				        		</div>
				        	</div><!-- Service info end -->
				      	<div class="ts-service-box-content text-justify">
					        <p>{{ item.description }}</p>
					        <p>
					        	{% if item.action_type == "select_service" %}
					        		<a class="btn btn-easypr bg-royal" href="{% url 'easypr_ng:get-started' item.category.name_slug item.name_slug %}">
					        			<i class="fa fa-caret-right"></i> &nbsp; {{ item.call_to_action }}</a>
					        	{% elif item.action_type == "submit_content" %}
					        		<a class="btn btn-easypr bg-royal" href="{% url 'easypr_ng:submit-content' item.category.name_slug item.name_slug %}">
					        			<i class="fa fa-caret-right"></i> &nbsp; {{ item.call_to_action }}</a>
					        	{% elif item.action_type == "request_service" %}
					        		<a class="btn btn-easypr bg-royal" href="{% url 'easypr_ng:request-service' item.category.name_slug item.name_slug %}">
					        			<i class="fa fa-caret-right"></i> &nbsp; {{ item.call_to_action }}</a>
					        	{% endif %}
		                    </p>       
				      	</div>
					   </div><!-- Service1 end -->
					</div><!-- Col 1 end -->

				{% endfor %}
	</section><!-- Main container end -->
		
{% endblock inner_content %}