easypr/urls.py
from zinnia.sitemaps import TagSitemap
from zinnia.sitemaps import EntrySitemap
from zinnia.sitemaps import CategorySitemap
from zinnia.sitemaps import AuthorSitemap


from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^easypr_admin/', include(admin.site.urls)),
    url('^',      include('easypr_ng.urls',      namespace  = "easypr_ng")),
    url('^admin/', include('easypr_admin.urls',   namespace  = "easypr_admin")),
    url('^',      include('easypr_general.urls', namespace  = "general")),
    url(r'^blog/', include('zinnia.urls')),
    url(r'^comments/', include('django_comments.urls'))
]

# sitemaps = {'tags': TagSitemap,
#             'blog': EntrySitemap,
#             'authors': AuthorSitemap,
#             'categories': CategorySitemap,}

# urlpatterns += [
#     'django.contrib.sitemaps.views',
#     url(r'^sitemap.xml$', 'index',
#         {'sitemaps': sitemaps}),
#     url(r'^sitemap-(?P<section>.+)\.xml$', 'sitemap',
#         {'sitemaps': sitemaps})]

easypr_general/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from easypr_general import views


# Create your urls here.
urlpatterns  =  [

             
	url(r'^$',                         				   views.indexView,                 name='homepage'),
	url(r'^who-we-are/$',                			   views.aboutUsView,               name='about-us'),
	url(r'^contact_us/$',      		   				   views.contactView,               name='contact-us'),
	url(r'^user/sign-up/$',         		   	       views.createUserAccount,         name='sign-up'),
	
	# url(r'^user/(?P<section_title>[-\w]+)$',           views.userDashboard,             name='user-dashboard'),
	# url(r'^user/(?P<section_title>[-\w]+)$',           views.userDashboard,             name='admin-dashboard'),
	
	url(r'^login/$',           		   				   views.loginView,          		name='login'),
	url(r'^logout/$',          		   				   views.logOutView,         		name='logout'),
	url(r'^careers/$',          	                   views.careersView,        		name='careers'),
	# url(r'^blog/$',          	                       views.careersView,            name='blog'),
	url(r'^subscribe/$',          	                   views.mailListView,           name='mailing-list-subscription'),
	url(r'^forgot-password/$', 						   views.forgotPasswordView,     name='forgot-password'),
    url(r'^reset-password/token=(?P<code>[-\w]+)/$',   views.resetPasswordView,  	 name='reset-password'),
	url(r'^confirm-registration/(?P<code>[-\w]+)/$',   views.confirmEmail, 			 name = 'confirm-email'),
	url(r'^thank-you/$',      					       TemplateView.as_view(template_name = "easypr_general/thank-you.html"), name='registration_success'),
	url(r'^frequently-asked-questions/$',          	   TemplateView.as_view(template_name = "easypr_general/faq.html"),  name='faq'),
	url(r'^how-it-works/$',          	               TemplateView.as_view(template_name = "easypr_general/how-it-works.html"),  name='how-it-works'),
	url(r'^terms-and-conditions/$',          	       TemplateView.as_view(template_name = "easypr_general/terms-and-conditions.html"),  name='terms-and-conditions'),

] 

# if DEBUG:
#     urlpatterns += [
#         url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
#             {'document_root': MEDIA_ROOT}),

#         url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#             {'document_root': STATIC_ROOT}),
# ]

easypr_ng/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from easypr_ng import views


urlpatterns  =  [     
	url(r'^$',                       views.indexView,                	     name='index'),
	url(r'^planner/step(?P<step>[-\d]+)/UID=(?P<anon_userID>[-\w\d]+)$',      	    views.strategyPlannerView,   name='strategy-planner'),
	url(r'^planner/$',      	                                        views.strategyPlannerIntroView,          name='strategy-planner-intro'),
	
	url(r'^news/(?P<post_id>[-\d]+)/(?P<title_slug>[-\w]+)/$',  		 views.readnewsView,            name = 'news-details'),
	
	url(r'^newsroom/$',                				                     views.newsRoomView,            name = 'newsroom'),
	url(r'^newsroom/category=(?P<category>[-\w\d]+)$',                	 views.newsRoomCatView,         name = 'newsroom-cat-view'),
	
	url(r'^post-comment/$',                                 	         views.postCommentView,         name = 'post-comment'),
	url(r'^post/comment/reply/$',                	                     views.postCommentReplyView,    name = 'post-reply'),

	url(r'^our-works/$',                				                 views.ourWorksView,            name = 'our-works'),
	url(r'^buy-package/press_material=(?P<press_material>[-\w]+)/package=(?P<package>[-\w]+)/$', views.buy_packageView, name = "buy-package"),
	url(r'^content-upload/preview/ref=(?P<transaction_id>[-\w]+)$',      views.previewPublicationView,  name = "preview-content"),
	url(r'^fetch-media-houses/$',                                        views.ajax_get_media_houses,        name = 'get-media-houses'),
	
	url(r'^fetch-blog-list/$',                                           views.get_blog_list,           name = 'get-blog-list'),
	
	url(r'^payment/ref=(?P<transaction_id>[-\w]+)$',                     views.Payment,                 name = 'payment'),
	
	url(r'^payment/save-details/$',                                      views.savePayInfo,             name = 'save-pay-details'),
	# url(r'^payment/save-details/ref=(?P<transaction_id>[-\w]+)/$',       views.savePayInfo,             name = 'save-pay-details'),
	
	url(r'^content-submission/success/$',                                views.confirmationView,        name = 'confirmation'),

	url(r'^services/(?P<service_category>[-\w]+)/$',         			 views.servicesView,            name = 'service-details'),
	url(r'^bespoke-bundle-plans/$',                                      views.bundlePlanView,          name = 'bundle-plans'),
	url(r'^marketing-bundles/buy/bundle=(?P<pk>[-\w]+)/$',               views.buyBundleView,           name = 'buy-bundle'),
	
	url(r'^(?P<category>[-\w]+)/(?P<item>[-\w]+)/pricing/$',             views.get_startedView,         name = 'get-started'),
	url(r'^(?P<category>[-\w]+)/(?P<item>[-\w]+)/submit-content/$',      views.submitContentView,       name = 'submit-content'),
	url(r'^(?P<category>[-\w]+)/(?P<item>[-\w]+)/submit-request/$',      views.requestServiceView,      name = 'request-service'),

	url(r'^ajax/create-purchase-for-bundle/$',                           views.createBundlePurchase,   name='create_purchase_for_bundle'),
	url(r'^ajax/make-card-payment/$',                                    views.makeCardPayment,        name='make-card-payment'),
	url(r'^ajax/make-card-payment/verify/(?P<txn_ref>[-\w]+)/$',         views.verifyCardPayment,      name='verify-card-payment'),



	# url(r'^(?P<section_title>[-\w]+)/$',      views.dashboardView,       name='admin-dashboard'),
	url(r'^user/(?P<section_title>[-\w]+)$',  views.userDashboard,       name='user-dashboard'),
	url(r'^ajax/ajax-load-page/$',            views.loadUserDashboard,   name='load-content-page'),
	url(r'^ajax/fetch-single-post/$',         views.fetchSinglePost,     name='fetch-post'),
	url(r'^ajax/save-changes/$',              views.updateUserPost,          name='update-post'),
	# url(r'^process/send-to-media/$',          views.send_post_to_media,  name='post-to-media'),
	url(r'^process/reject-post/$',            views.rejectPost,          name='reject-post'),
	url(r'^process/delete-post/(?P<post_pk>[-\w]+)/$',            views.deletePost,      name='delete-post'),
	] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

easypr_ng/models.py
from django.contrib.sites.models import Site
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User 
from easypr_general.models_field_choices import *
from easypr_general.models import UserAccount
from django.db.models import Q, Sum
import random
# from django.contrib.auth.models import User 
from easypr.settings import VAT
from easypr.settings import NAIRA_DOLLAR_RATE as exchange_rate
from easypr_general.custom_classes import Hasher
# from Crypto.Cipher import AES


class MediaPlatform(models.Model):
  name        =   models.CharField(max_length = 60)
  name_slug   =   models.CharField(max_length = 75)
  active      =   models.BooleanField(default = True)
 
  def __unicode__(self):
    return '%s' %(self.name)

  def save(self, *args, **kwargs):
    self.name_slug = slugify(self.name)
    super(MediaPlatform, self).save(*args, **kwargs)
    return True


class Sector(models.Model):
  name           =      models.CharField(max_length = 60)
  name_slug      =      models.CharField(max_length = 75)
  active         =      models.BooleanField(default = True)
 
  def __unicode__(self):
    return '%s' %(self.name)

  def save(self, *args, **kwargs):
    self.name_slug   =   slugify(self.name)
    super(Sector, self).save(*args, **kwargs)


class MediaContact(models.Model):
  media_house              =           models.ForeignKey('MediaHouse')
  first_name               =           models.CharField(max_length = 125)
  last_name                =           models.CharField(max_length = 125)
  date_added               =           models.DateTimeField(auto_now_add = True)
  email                    =           models.CharField(max_length = 225)
  phone_number             =           models.CharField(max_length = 15, null = True, blank = True)

  def __unicode__(self):
    return '%s,%s,%s' %(self.media_house.name, self.first_name + self.last_name, self.email)

  def get_media_house(self):
    return self.media_house.name

  def get_full_name(self):
    return '%s %s' %(self.first_name, self.last_name)

class MediaHouse(models.Model):
  name                =           models.CharField(max_length = 200)
  name_slug           =           models.CharField(max_length = 200)
  date_added          =           models.DateTimeField(auto_now_add = True)
  platform            =           models.ManyToManyField('MediaPlatform')
  active              =           models.BooleanField(default = True)



  def save(self, *args, **kwargs):
    self.name_slug  = slugify(self.name)
    super(MediaHouse, self).save(*args, **kwargs)


  def __unicode__(self):
    return '%s' %(self.name)


  def get_contacts(self):
  	return self.mediacontact_set.all()


class PressMaterial(models.Model):
  name_slug                =         models.CharField(max_length = 150)
  media_type               =         models.CharField(max_length = 150)
  price_per                =         models.FloatField(default = 0.0)
  date_added               =         models.DateTimeField(auto_now_add = True)
  caption                  =         models.CharField(max_length = 125)

  def __unicode__(self):
    return '%s' %(self.media_type)

  def save(self, *args, **kwargs):
    self.name_slug  = slugify(self.media_type)
    super(PressMaterial, self).save(*args, **kwargs)


class PublicationManager(models.Manager):

  def fetch_published_articles(self):
    return self.get_queryset().filter(Q(status = "Published"), Q(deleted = False, completed = True))

  def fetch_new_articles(self):
      return self.get_queryset().filter(status = "New", deleted = False, completed = True)

  def fetch_status_articles(self, status):
    return self.get_queryset().filter(Q(status = status), Q(deleted = False, completed = True))

  def fetch_all_articles(self):
    return self.get_queryset().filter(deleted = False, completed = True)

  def fetch_pub_for_user(self, user, status):
    if not status == 'all':
      response =  self.get_queryset().filter(Q(posted_by = user), Q(status = status),Q(deleted = False)) 
    # elif status == "pending":
    #   response =  self.get_queryset().filter(Q(posted_by = user), Q(deleted = False), Q(status = status))
    else:
      response =  self.get_queryset().filter(Q(posted_by = user, deleted = False))
    print "query response ", response
    return response


class Publication(models.Model):
    transaction_id                  =              models.CharField(max_length = 15)
    post_title                      =              models.CharField(max_length = 175)
    title_slug                      =              models.CharField(max_length = 200)
    status                          =              models.CharField(max_length = 50, choices = PUB_STATUS)
    post_body                       =              models.TextField(max_length = 3000, null = True, blank = True)
    person_to_quote                 =              models.CharField(max_length = 125, null = True, blank = True)
    persons_position                =              models.CharField(max_length = 125, null = True, blank = True)
    uploaded_text                   =              models.FileField(upload_to ='publication/text_file', null=True, blank = True)
    posted_by                       =              models.ForeignKey(User)
    platform                        =              models.ForeignKey('MediaPlatform', verbose_name = "Media platform", null = True, blank = True)
    sector                          =              models.ForeignKey('Sector', verbose_name = "Media sector", null = True, blank = True)
    press_material                  =              models.ForeignKey('PressMaterial', verbose_name = "Media category", null = True, blank = True)
    published_by                    =              models.ForeignKey(User, related_name="Edited_and_published_by", null = True, blank = True)
    assigned_to                     =              models.ForeignKey(User, related_name = "Third_party_Editor", null = True, blank = True)
    
    date_published                  =              models.DateTimeField(auto_now_add = False, null=True, blank=True)
    date_posted                     =              models.DateTimeField(auto_now_add = True)

    # media_urls                      =              models.ManyToManyField('Redirect_url', )
    site                            =              models.ManyToManyField(Site)
    # pictures                        =              models.ManyToManyField('PublicationImage')
    media_houses                    =              models.ManyToManyField('MediaHouse')
    
    deleted                         =              models.BooleanField(default = False)
    publish_online                  =              models.BooleanField("Do you also want online publication of the chosen media? ", default = False)
    completed                       =              models.BooleanField(default = False)
    objects                         =              PublicationManager()
    rejection_reason                =              models.CharField(max_length = 350, null = True, blank = True)
    is_edited                       =              models.BooleanField(default = False)
    edited_by                       =              models.CharField(max_length  =  125, null = True, blank = True)
    archived_original_post          =              models.TextField(max_length = 3000, null = True, blank = True)
    archived_post_title             =              models.CharField(max_length = 175, null = True, blank = True)

    def save(self, *args, **kwargs):
        self.title_slug  = slugify(self.post_title)
        super(Publication, self).save(*args, **kwargs)

    def __unicode__(self):
        return '%s' %(self.post_title)


    def get_media_urls(self):
    	return [link.url for link in self.redirect_url_set.all()]


    def get_media_houses(self):
      media = [media.name for media in self.media_houses.all()]
      return ", ".join(media)


    def get_media_contacts(self):
      contact_dict =  {}
      contact_list =  []
      for media in self.media_houses.all():
        for contact in media.mediacontact_set.all():
          contact_list.append(contact)
      return contact_list


    def get_images(self):
      return self.publicationimage_set.all()


    def featured_image(self):
      try:
        return self.get_images()[random.choice(range(0, self.get_images().count() -1))].image.url
      except:
        return None # return default avater

    def get_post_comments(self):
      return self.comment_set.all()

    def read_uploaded_document(self):
    	pass

    def has_image(self):
      return self.get_images().count() > 0


class PublicationImage(models.Model):
  post       =     models.ForeignKey('Publication', null = True, blank = True)
  image      =     models.ImageField(upload_to ='publication', null = True, blank = True)      
  caption    =     models.CharField(max_length = 200, null = True, blank =  True)

  def __unicode__(self):
    return '%s' %(self.post.post_title)


class RequestImage(models.Model):
  request     =     models.ForeignKey('ServiceRequest', null = True, blank = True)
  image       =     models.ImageField(upload_to ='service_request', null = True, blank = True)      
  caption     =     models.CharField(max_length = 200, null = True, blank =  True)


class Redirect_url(models.Model):
  url     =        models.CharField(max_length = 200, blank = True, null = True, default= None)
  post    =        models.ForeignKey('Publication', null=True, blank = True)

  def __unicode__(self):
    return '%s' %(self.url)


class Comment(models.Model):
  post            =     models.ForeignKey('Publication')
  posted_by       =     models.ForeignKey(User)
  date_posted     =     models.DateTimeField(auto_now_add = True)
  comment         =     models.TextField(max_length = 1000)
  website         =     models.CharField(max_length = 150, null = True, blank = True)


class CommentReply(models.Model):

easypr_ng/templates/useraccount/user-dashboard.html
{% extends 'easypr_general/base.html' %}
{% load staticfiles %}
{% load base_custom_filters %}

{% block title %}User Dashboard{% endblock title %}
{% block inner_content %}
	<section id="main-container" class="main-container">
		<div class="container">
			<div class="dashboard">
				<div class="row">
					<div class="col-md-3">
						<div class="left-nav">
							<h5 class="bg-royal text-white" style="padding: 8px; margin-bottom: 0px;">DASHBOARD</h5>
							<ul class = "unstyled" style="background-color: #025cb7;">
								<li><i class="fa fa-clipboard" aria-hidden="true"></i> &nbsp; <a href="{% url 'easypr_ng:user-dashboard' 'my-submissions' %}">Submissions</a></li>
								<li><i class="fa fa-database" aria-hidden="true"></i> &nbsp;<a href="{% url 'easypr_ng:user-dashboard' 'archive' %}">Archive</a></li>
								<li><i class="fa fa-line-chart" aria-hidden="true"></i> &nbsp;<a href="{% url 'easypr_ng:user-dashboard' 'analytics' %}">Analytics</a></li>
								<li><i class="fa fa-user" aria-hidden="true"></i> &nbsp;<a href="{% url 'easypr_ng:user-dashboard' 'profile' %}">Profile</a></li>
								<li><i class="fa fa-credit-card" aria-hidden="true"></i> &nbsp;<a href="{% url 'easypr_ng:user-dashboard' 'subscription' %}">Subscription</a></li>
								<li><i class="fa fa-cog" aria-hidden="true"></i> &nbsp;<a href="{% url 'easypr_ng:user-dashboard' 'settings' %}">Settings</a></li>
								<li class="login-list">
								<div class="gap-20"></div>
									<a href="{% url 'general:logout' %}" class="btn btn-easypr bg-royal"><i class="fa fa-sign-out" aria-hidden="true"></i> &nbsp; Logout</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="col-md-9" style="padding: 0px; ">
						<div class="row" role="search form">
							<div class="col-md-6 pull-right">
							<form>
								<div class="input-group">
									<input type="text"  class="form-control"placeholder="search by transaction No." name="search-item">
                					<span class="input-group-addon">
                						<a href="#" class="btn bg-royal text-white" >search </a> 
                						<!-- <input type="submit" class="btn bg-royal text-white" value="Search" style="margin: none !important;" name="submit-search"> -->
                					</span>
                				</div>
							</form>
							</div>
						</div>
						<div class="row">
							{% if section_title == "my-submissions" %}
								<!-- <h5>{{ section_title|upper|strip_chars:"-" }}</h5> -->
								<ul class="nav nav-tabs" style="border-bottom: thin solid #b3b3b3; ">
									<li class="bundle-tab-spaced active" onclick="load_page('submissions','new','id_inner_content')">
										<a data-toggle="tab" href="#">New</a>
									</li>
									<li class="bundle-tab-spaced" onclick="load_page('submissions','in-progress','id_inner_content')">
										<a data-toggle="tab" href="#">In Progress</a>
									</li>
									<li class="bundle-tab-spaced" onclick="load_page('submissions','pending','id_inner_content')">
										<a data-toggle="tab" href="#">Saved to Draft</a>
									</li>
									<li class="bundle-tab-spaced" onclick="load_page('submissions','published','id_inner_content')">
										<a data-toggle="tab" href="#">Published</a>
									</li>
									<li class="bundle-tab-spaced" onclick="load_page('submissions','rejected','id_inner_content')">
										<a data-toggle="tab" href="#">Rejected</a>
									</li>
								</ul>
							{% else %}
								<h5 class="section_title">{{ section_title|strip_chars:"-"}}</h5>
							{% endif %}
						</div>

						<div class="gap-20"></div>

						<div class="row inner-content" id="id_inner_content">
							{% include 'useraccount/user-submissions.html' %}
						</div> <!-- ends inner-content -->
					</div> <!-- ends right panel -->
				</div>
			</div>
		</div><!-- Conatiner end -->
	</section><!-- Main container end -->
{% endblock inner_content %}


{% block modal %}
	{% include 'snippets/post-preview.html' with modal_Id='preview-edit-post' %}
	{% include 'snippets/media-contacts-modal.html' with modal_Id='select_media_contact' %}
	{% include 'snippets/rejection_reason.html' with modal_Id='rejection_reason' %}
	{% include 'snippets/publish_post.html' with modal_Id='post_urls' %}
{% endblock modal %}





{% block inline_scripts %}
	<script type="text/javascript" src="{% static 'easypr/js/jquery.js' %}"></script>
	<script>
		function load_page(content_type, option, div_to_populate){
			var content = content_type;
			var content_div  =   $("#" + div_to_populate);
			content_div.html("<p class='text-success'><strong> Fetching data ...</strong></p>");
			$.ajax({
				url:  "{% url 'easypr_ng:load-content-page' %}",
				type: "GET",
				data: {content:content, option:option},
				success: function(data){
					content_div.html(data);
				},
				error: function(){
					content_div.html("Error Loading page, please try again");
				}
			})
		}
	</script>
	<script>
		$('body').on('click', '.preview-post', function(){
			var post_id = $(this).attr('post_id');
			$.ajax({
				url:  "{% url 'easypr_ng:fetch-post' %}",
				type: "GET",
				data: {post_id:post_id, action:'preview'},
				success: function(data){
					// alert(data.post_body);
					$("#id_post_title").val(data.post_title);
					$("#id_post_body").val(data.post_body);
					$("#id_post_id").val(data.pk);
					$("#is_edited").val(0);
					$("#preview-edit-post").modal('show');
				},
				error: function(){
					alert('failed ');
				}
			})
		})
	</script>

	<script>
		$('body').on('click', '.send-to-media', function(){
			var post_id = $(this).attr('post_id');
			$.ajax({
				url:  "{% url 'easypr_ng:fetch-post' %}",
				type: "GET",
				data: {post_id:post_id, action:'send_to_media'},
				success: function(data){
					$("#id_media_contacts").html(data);
					$("#active_post_id").val(post_id);
					$("#select_media_contact").modal('show');
				},
				error: function(){
					alert('failed ');
				}
			})
		})
	</script>

	<script>
		$('body').on('click', '.publish', function(){
			var post_id = $(this).attr('post_id');
			$("#publish_post_id").val(post_id);
			$("#post_urls").modal('show');
		})

		$('body').on('click','#add_url_field', function(){
	        var newfield = document.createElement('div');
	        newfield.innerHTML = "<input type = 'text' name='post_url[]' class='form-control' placeholder = 'Enter media url. eg. http://vanguardngr.com/new-topic-here' /><br/>";
	        document.getElementById('id_post_urls').appendChild(newfield);
	    })
	</script>


	<script>
	// check if changes have been made to post title or body
		count = 0;
		$('body').on('keypress', '#id_post_title, #id_post_body', function(){
			count++;
			$("#is_edited").val(count);
			if (parseInt(count) > 0){
				$("#is_edited").val("edited");
			}	
		})

		$("#id_discard_changes").on('click', function(){
			if ($("#is_edited").val() == "edited"){
				return confirm("Changes you made will be lost. Are you sure you want to close this page?");
			}
		})

		$("#id_save_changes").on('click', function(){
			if ($("#is_edited").val() == "edited"){
				return confirm("Save changes to this post?");
			}
		})

		$('body').on('click', '#id_select_all', function(){
			$("#id_select_all").is(':checked') ? $(".media_contact").attr('checked', true) : $(".media_contact").attr('checked', false);
		})

		$('body').on('click', '.delete_post', function(){
			return confirm("Are you sure you want to discard this post. \n Deleted posts cannoot be recorvered.");
		})

		$('body').on('click', '.reject-post', function(){
			var post_id = $(this).attr('post_id');
			$("#reject_post_id").val(post_id);
			$("#rejection_reason").modal('show');
		})

		
	</script>
{% endblock inline_scripts %}

easypr_ng/templates/useraccount/user-submissions.html
{% load base_custom_filters %}
{% load staticfiles %}

{% for item in posts %}
	<div class="row post_strip text-dark {% if forloop.counter|is_even %} bg-even {% endif %}">
		<div class="col-md-2">
			<img class="thumbnail" src="{% if item.featured_image %}{{ item.featured_image }}{% else %}{% static 'easypr/images/icons/no-image-sm.png' %} {% endif %}" alt="easyPR Nigeria">
		</div>
		<div class="col-md-8">

			<strong class="text-primary"><a href="#" post_id = "{{ item.pk }}" {% if item.status.lower == "new" %} class="preview-post" {% endif %}>{{ item.post_title|title }}</strong><br>
			<small class="text-justify">{{ item.post_body|truncatewords:30 }}</small><br>
			<div class="bg-royal text-white" style="padding:3px;"><small>Selected Media:</small> <strong>{{ item.get_media_houses|title|truncatewords:12 }}</strong></div><br>
		</div>
		<div class="col-md-2 text-center" style="padding-top: 50px;">
			{% if item.status.lower == "new" %}
				<p><a href="#" post_id = "{{ item.pk }}" title="preview" class="preview-post"><i class="fa fa-search" ></i></a>
				{% if request.user.is_admin or request.user.is_superuser %}
					<a href="#" post_id = "{{ item.pk }}" title="Send to media house" class="send-to-media"><i class="fa fa-newspaper-o space-left"></i></a>
					<a href="#" post_id = "{{ item.pk }}" title="Send to Ext Editor" class="send-to-ext-editor"><i class="fa fa-external-link space-left" ></i></a>
				{% endif %}
				<a href="#" post_id = "{{ item.pk }}" class="text-danger reject-post" title="Reject"><i class="fa fa-trash space-left"></i></a></p>
			{% elif item.status.lower == "sent_to_external_editor" or item.status.lower == "processing" and request.user.is_superuser %}
				<a href="#" post_id = "{{ item.pk }}" class="publish" title="publish post"><i class="fa fa-clipboard space-left" ></i></a><br>
			{% elif item.status.lower == "published" %}
				<a href="{% url 'easypr_ng:news-details' item.pk item.title_slug %}" class="btn btn-sm btn-success" title="view post in newsroom">View post</a>
			{% elif item.status.lower == "pending" %}
				<a href="{% url 'easypr_ng:preview-content' item.transaction_id %}" class="text-success" title="continue editing"><i class="fa fa-pencil space-left" ></i></a>
				<a href="{% url 'easypr_ng:delete-post' item.pk %}" class="text-danger delete_post" title="delete post"><i class="fa fa-trash space-left" ></i></a>
			{% endif %}

		</div>
	</div>
{% empty %}
	<p>No post found.</p>
{% endfor %}