easypr/urls.py
from zinnia.sitemaps import TagSitemap
from zinnia.sitemaps import EntrySitemap
from zinnia.sitemaps import CategorySitemap
from zinnia.sitemaps import AuthorSitemap


from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^easypr_admin/', include(admin.site.urls)),
    url('^',      include('easypr_ng.urls',      namespace  = "easypr_ng")),
    url('^admin/', include('easypr_admin.urls',   namespace  = "easypr_admin")),
    url('^',      include('easypr_general.urls', namespace  = "general")),
    url(r'^blog/', include('zinnia.urls')),
    url(r'^comments/', include('django_comments.urls'))
]

# sitemaps = {'tags': TagSitemap,
#             'blog': EntrySitemap,
#             'authors': AuthorSitemap,
#             'categories': CategorySitemap,}

# urlpatterns += [
#     'django.contrib.sitemaps.views',
#     url(r'^sitemap.xml$', 'index',
#         {'sitemaps': sitemaps}),
#     url(r'^sitemap-(?P<section>.+)\.xml$', 'sitemap',
#         {'sitemaps': sitemaps})]

easypr_admin/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from easypr_admin import views


# Create your urls here.
urlpatterns  =  [

             
	# url(r'^/admin/$',                         				views.dashboardView,      name='admin-dashboard'),
	url(r'^(?P<section_title>[-\w]+)/$',               views.dashboardView,                name='admin-dashboard'),
	
	url(r'^ajax/ajax-load-page/$',                    views.ajaxLoadDashboard,             name='load-content-page'),
	url(r'^ajax/fetch-single-post/$',                 views.fetchSinglePost,               name='fetch-post'),
	url(r'^ajax/save-changes/$',                      views.updatePost,                    name='update-post'),
	url(r'^process/send-to-media/$',                  views.send_post_to_media,            name='post-to-media'),
	url(r'^process/reject-post/$',                    views.rejectPost,                    name='reject-post'),
	url(r'^process/publish-post/$',                   views.publishPost,                   name='publish-post'),


	# url(r'^about_us/$',                					views.aboutUsView,        name='about_us'),
	# # url(r'^services/$',                                 views.servicesView,       name='services'),
	# url(r'^newsroom/$',                					views.newsroomView,       name='newsroom'),
	# url(r'^contact_us/$',      		   					views.contactView,        name='contact_us'),
	# url(r'^sign_up/$',         		   					views.signUpView,         name='sign_up'),
	# url(r'^login/$',           		   					views.loginView,          name='login'),
	# url(r'^logout/$',          		   					views.logoutView,         name='logout'),
	# url(r'^accounts/posts/$',          	                views.dashboardView,      name='user-dashboard'),
	# url(r'^terms-and-conditions/$',          		    views.TandCView,          name='tandc'),
	# # url(r'^client/feedback/$',                          views.clientFeedback,           name = 'user-feedback'),
	# url(r'^article/create/new/$',      					views.createArticleView,  name='create-article'),
	# url(r'^services/$',                                 TemplateView.as_view(template_name = "yadel/general/services.html"), name='services'),
	# url(r'^thank-you/$',      					        TemplateView.as_view(template_name = "yadel/general/thank-you.html"), name='registration_success'),
	# url(r'^confirm-registration/(?P<code>[-\w]+)/$',    views.confirmEmail, name = 'confirm-email'),
	# # url(r'^news/(?P<pk>[-\d]+)/(?P<news_title>[-\w]+)/url=(?P<url_link>[-\w]+)/$',  views.loadExternalNews, name = 'news-details')

	# url(r'^news/(?P<pk>[-\d]+)/(?P<news_title>[-\w]+)/$',  views.loadExternalNews, name = 'news-details')

	] 
	 # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

easypr_general/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from easypr_general import views


# Create your urls here.
urlpatterns  =  [

             
	url(r'^$',                         				   views.indexView,                 name='homepage'),
	url(r'^who-we-are/$',                			   views.aboutUsView,               name='about-us'),
	url(r'^contact_us/$',      		   				   views.contactView,               name='contact-us'),
	url(r'^user/sign-up/$',         		   	       views.createUserAccount,         name='sign-up'),
	
	# url(r'^user/(?P<section_title>[-\w]+)$',           views.userDashboard,             name='user-dashboard'),
	# url(r'^user/(?P<section_title>[-\w]+)$',           views.userDashboard,             name='admin-dashboard'),
	
	url(r'^login/$',           		   				   views.loginView,          		name='login'),
	url(r'^logout/$',          		   				   views.logOutView,         		name='logout'),
	url(r'^careers/$',          	                   views.careersView,        		name='careers'),
	# url(r'^blog/$',          	                       views.careersView,            name='blog'),
	url(r'^subscribe/$',          	                   views.mailListView,           name='mailing-list-subscription'),
	url(r'^forgot-password/$', 						   views.forgotPasswordView,     name='forgot-password'),
    url(r'^reset-password/token=(?P<code>[-\w]+)/$',   views.resetPasswordView,  	 name='reset-password'),
	url(r'^confirm-registration/(?P<code>[-\w]+)/$',   views.confirmEmail, 			 name = 'confirm-email'),
	url(r'^thank-you/$',      					       TemplateView.as_view(template_name = "easypr_general/thank-you.html"), name='registration_success'),
	url(r'^frequently-asked-questions/$',          	   TemplateView.as_view(template_name = "easypr_general/faq.html"),  name='faq'),
	url(r'^how-it-works/$',          	               TemplateView.as_view(template_name = "easypr_general/how-it-works.html"),  name='how-it-works'),
	url(r'^terms-and-conditions/$',          	       TemplateView.as_view(template_name = "easypr_general/terms-and-conditions.html"),  name='terms-and-conditions'),

] 

# if DEBUG:
#     urlpatterns += [
#         url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
#             {'document_root': MEDIA_ROOT}),

#         url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#             {'document_root': STATIC_ROOT}),
# ]

easypr_admin/models.py
from django.db import models

# Create your models here.

easypr_ng/forms.py
from django import forms
from django.contrib.auth.models import User
from easypr_ng.models import *
from easypr_general.models import *
from easypr_general.models_field_choices import *
# from django.forms import modelform_factory,Select,TextInput,Textarea,CheckboxInput,EmailInput
# from django
# from multiupload.fields import MultiFileField




class ContentUploadForm(forms.ModelForm):
	post_title         =    forms.CharField(max_length = 200, widget=forms.TextInput(attrs=
					        {'class' : 'form-control no-border-radius title bg-white', 'placeholder': 'Enter post title','required':'required', 'maxLength':200}))	
	# platform       			 =    forms.CharField(max_length = 128, widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder': 'Last Name', 'required':'required'}))
	person_to_quote    =    forms.CharField(max_length = 128, widget=forms.TextInput(attrs=
						    {'class' : 'form-control no-border-radius bg-white', 'placeholder': 'Person to quote', 'required':'required'}))
	persons_position   =    forms.CharField(max_length = 128, widget=forms.TextInput(attrs=
							{'class' : 'form-control no-border-radius bg-white', 'placeholder': 'Position', 'required':'required'}))
	# media_houses             =    forms.CharField(max_length = 128, widget=forms.Select(attrs={'class' : 'form-control', 'placeholder': 'Last Name', 'required':'required'}))
	post_body          =    forms.CharField(max_length = 3000, widget=forms.Textarea(attrs=
							{'class' : 'form-control no-border-radius bg-white', 'placeholder': 'Type or copy and paste content here','required':'required','rows':20, 'maxLength':3000}))
	publish_online     =    forms.CharField(max_length = 10, widget=forms.CheckboxInput(attrs={'value' : 'false'}))
	


	class Meta:
		model = Publication
		fields = ('post_title','person_to_quote', 'persons_position','post_body','publish_online',)





class BizInfoForm(forms.ModelForm):
	# business_type      =    forms.ModelChoiceField(queryset = BUSINESS_TYPE, widget=forms.Select(attrs={'class' : 'form-control no-border-radius title bg-white', 'required':'required'}))
	business_type      =    forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius title bg-white', 'required':'required'}))
	company_type       =    forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius title bg-white', 'required':'required'}))
	is_pr_agent        =    forms.CharField(max_length = 10, widget=forms.CheckboxInput(attrs={'value' : 'false'}))
	size_of_pr_team    =    forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius title bg-white','required':'required'}))

	class Meta:
		model = PRStrategy
		fields  =  ('business_type','company_type','is_pr_agent','size_of_pr_team')



class TargetAudienceForm(forms.ModelForm):
	target_audience 	=       forms.CharField(max_length = 1000, widget=forms.Textarea(attrs=
							{'class' : 'form-control no-border-radius bg-white', 'required':'required','rows':20}))
	pr_goals        	=       	forms.CharField(max_length = 1000, widget=forms.Textarea(attrs=
									{'class' : 'form-control no-border-radius bg-white', 'required':'required','rows':20}))
	frequency_of_pr 	=       	forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius title bg-white', 'required':'required'}))
	target_audience_location  =      forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius title bg-white', 'required':'required'}))
   



	class Meta:
		model = PRStrategy
		fields = ('target_audience','pr_goals','frequency_of_pr','target_audience_location',)



class ServiceRequestForm(forms.ModelForm):
	# service_type      =    forms.CharField(max_length = 100, widget=forms.Select(choices = SERVICE_TYPE, attrs={'class' : 'form-control no-border-radius border-thick', 'required':'required'}))
	# sector            =    forms.CharField(max_length = 100, widget=forms.Select(choices = ECONOMY_SECTOR, attrs={'class' : 'form-control no-border-radius border-thick', 'required':'required'}))
	# brief_description   =    forms.CharField(max_length = 450, required=False, widget=forms.Textarea(attrs={'class' : 'form-control no-border-radius bg-white border-thick','rows':5,'placeholder':"Briefly describe the service you want."}))
	# brief_description   =    forms.CharField(max_length = 450, required=False, widget=forms.Textarea(attrs={'class' : 'form-control no-border-radius bg-white border-thick','rows':5,'placeholder':"Briefly describe the service you want."}))
	# sector            =    forms.CharField(max_length = 100, widget=forms.Select(choices = MEDIA_PLATFORM, attrs={'class' : 'form-control no-border-radius border-thick', 'required':'required'}))
	# time_service_needed  =    forms.DateField(widget=forms.DateInput(attrs={'class' : 'form-control no-border-radius border-thick', 'required':'required'}))
	# preferred_call_time  =    forms.CharField(max_length = 100, widget=forms.Select(attrs={'class' : 'form-control no-border-radius border-thick', 'required':'required'}))
	# allow_call           =    forms.CharField(max_length = 100, widget=forms.CheckboxInput(attrs={'class' : 'form-control no-border-radius border-thick', 'required':'required'}))
	contact_person     	 =    forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius bg-white border-thick', 'required':'required'}))
	contact_email     	 =    forms.CharField(max_length = 200, widget=forms.EmailInput(attrs={'class' : 'form-control no-border-radius bg-white border-thick', 'required':'required'}))
	phone_number     	 =    forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius bg-white border-thick', 'required':'required'}))
	# ticket_number     	 =    forms.CharField(max_length = 14, widget=forms.TextInput(attrs={'class' : 'form-control no-border-radius bg-white border-thick', 'required':'required'}))


	# def __init__(self, *args, **kwargs):
	# 	super(ServiceRequestForm, self).__init__(*args, **kwargs)
	# 	self.fields['brief_description'].required = self.instance.pk is None



	class Meta:
		model  = ServiceRequest
		fields = ('contact_person','contact_email','phone_number')
		# fields = ('brief_description', 'contact_person','contact_email','phone_number')

easypr_admin/templates/easypr_admin/dashboard.html
{% extends 'easypr_general/base.html' %}
{% load staticfiles %}
{% load base_custom_filters %}

{% block title %}Dashboard{% endblock title %}
{% block inner_content %}
	<section id="main-container" class="main-container">
		<div class="container">
			<div class="dashboard">
				<div class="row">
					<div class="col-md-3">
						<div class="left-nav">
							<h5 class="bg-royal text-white" style="padding: 8px; margin-bottom: 0px;">DASHBOARD
								<button type="button" class="pull-right bg-royal text-white dashboard-toggle" data-toggle="collapse" data-target=".dashboard-nav">
							        <span class="sr-only">Toggle navigation</span>
							        <i class="fa fa-eye" aria-hidden="true"></i>
				    			</button>
				    		</h5>
							<ul class = "unstyled dashboard-nav" style="background-color: #025cb7;">
								<li><i class="fa fa-clipboard" aria-hidden="true"></i> &nbsp; <a href="{% url 'easypr_admin:admin-dashboard' 'submissions' %}">Submissions</a></li>
								<li><i class="fa fa-database" aria-hidden="true"></i> &nbsp;<a href="{% url 'easypr_admin:admin-dashboard' 'user-manager' %}">User Manager</a></li>
								<li><i class="fa fa-line-chart" aria-hidden="true"></i> &nbsp;<a href="{% url 'easypr_admin:admin-dashboard' 'content-manager' %}">Content Manager</a></li>
								<li><i class="fa fa-user" aria-hidden="true"></i> &nbsp;<a href="{% url 'easypr_admin:admin-dashboard' 'blog-manager' %}">Blog Manager</a></li>
								<li><i class="fa fa-credit-card" aria-hidden="true"></i> &nbsp;<a href="{% url 'easypr_admin:admin-dashboard' 'affiliate-manager' %}">Affiliate Manager</a></li>
								<li><i class="fa fa-cog" aria-hidden="true"></i> &nbsp;<a href="{% url 'easypr_admin:admin-dashboard' 'analytics' %}">Analytics</a></li>
								<li><i class="fa fa-cog" aria-hidden="true"></i> &nbsp;<a href="{% url 'easypr_admin:admin-dashboard' 'accounts-manager' %}">Accounts Manager</a></li>
								<li class="login-list">
								<div class="gap-20"></div>
									<a href="{% url 'general:logout' %}" class="btn btn-easypr bg-royal"><i class="fa fa-sign-out" aria-hidden="true"></i> &nbsp; Logout</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="col-md-9" style="padding: 0px; ">
						<div class="row" role="search form">
							<div class="col-md-6 pull-right">
							<form>
								<div class="input-group">
									<input type="text"  class="form-control"placeholder="search by transaction No." name="search-item">
                					<span class="input-group-addon">
                						<a href="#" class="btn bg-royal text-white" >search </a> 
                						<!-- <input type="submit" class="btn bg-royal text-white" value="Search" style="margin: none !important;" name="submit-search"> -->
                					</span>
                				</div>

								<!-- <div class="col-sm-9">
									<input type="text"  class="form-control"placeholder="search by transaction No." name="search-item">
								</div>
								<div class="col-sm-3">
									<input type="submit" class="btn btn-easypr" value="Search" name="submit-search">
								</div> -->
							</form>
							</div>
						</div>
						<div class="row">
							{% if section_title == "submissions" %}
								<h5>{{ section_title|upper|strip_chars:"-" }}</h5>
								<ul class="nav nav-tabs" style="border-bottom: thin solid #b3b3b3; ">
									<li class="bundle-tab-spaced default" onclick="load_page('submissions','all','id_inner_content')">
										<a data-toggle="tab" href="#">All</a>
									</li>
									<li class="bundle-tab-spaced" onclick="load_page('submissions','new','id_inner_content')">
										<a data-toggle="tab" href="#">New</a>
									</li>
									<li class="bundle-tab-spaced" onclick="load_page('submissions','processing','id_inner_content')">
										<a data-toggle="tab" href="#">Processing</a>
									</li>
									<li class="bundle-tab-spaced" onclick="load_page('submissions','sent_to_ext_editor','id_inner_content')">
										<a data-toggle="tab" href="#">Sent to Ext Editor</a>
									</li>
									<li class="bundle-tab-spaced" onclick="load_page('submissions','published','id_inner_content')">
										<a data-toggle="tab" href="#">Published</a>
									</li>
									<li class="bundle-tab-spaced" onclick="load_page('submissions','rejected','id_inner_content')">
										<a data-toggle="tab" href="#">Rejected</a>
									</li>
								</ul>
							{% elif section_title == "user-manager" %}
								<h5>{{ section_title|upper|strip_chars:"-" }}</h5>
								<ul class="nav nav-tabs" style="border-bottom: thin solid #b3b3b3; ">
									<li class="bundle-tab-spaced default" onclick="load_page('users','staff','id_inner_content')" onclick="load_page()"><a data-toggle="tab" href="#">Staff</a></li>
									<li class="bundle-tab-spaced" onclick="load_page('users','clients','id_inner_content')"><a data-toggle="tab" href="#">Clients</a></li>
									<li class="bundle-tab-spaced" onclick="load_page('users','media contacts','id_inner_content')"><a data-toggle="tab" href="#">Media Contacts</a></li>
								</ul>
							{% else %}
								<h5 class="section_title">{{ section_title|strip_chars:"-"}}</h5>
							{% endif %}
						</div>

						<div class="gap-20"></div>

						<div class="row inner-content" id="id_inner_content">
							{% include inset_template %}
						</div> <!-- ends inner-content -->
					</div> <!-- ends right panel -->
				</div>
			</div>
		</div><!-- Conatiner end -->
	</section><!-- Main container end -->
{% endblock inner_content %}


{% block modal %}
	{% include 'snippets/post-preview.html' with modal_Id='preview-edit-post' %}
	{% include 'snippets/media-contacts-modal.html' with modal_Id='select_media_contact' %}
	{% include 'snippets/rejection_reason.html' with modal_Id='rejection_reason' %}
	{% include 'snippets/publish_post.html' with modal_Id='post_urls' %}
{% endblock modal %}


{% block inline_scripts %}
	<script type="text/javascript" src="{% static 'easypr/js/jquery.js' %}"></script>
	<script>
		function load_page(content_type, option, div_to_populate){
			var content = content_type;
			var content_div  =   $("#" + div_to_populate);
			$.ajax({
				url:  "{% url 'easypr_admin:load-content-page' %}",
				type: "GET",
				data: {content:content, option:option},
				success: function(data){
					content_div.html(data);
				},
				error: function(){
					content_div.html("Error Loading page, please try again");
				}
			})
		}
	</script>
	<script>
		$('body').on('click', '.preview-post', function(){
			var post_id = $(this).attr('post_id');
			$.ajax({
				url:  "{% url 'easypr_admin:fetch-post' %}",
				type: "GET",
				data: {post_id:post_id, action:'preview'},
				success: function(data){
					// alert(data.post_body);
					$("#id_post_title").val(data.post_title);
					$("#id_post_body").val(data.post_body);
					$("#id_post_id").val(data.pk);
					$("#is_edited").val(0);
					$("#preview-edit-post").modal('show');
				},
				error: function(){
					alert('failed ');
				}
			})
		})
	</script>

	<script>
		$('body').on('click', '.send-to-media', function(){
			var post_id = $(this).attr('post_id');
			$.ajax({
				url:  "{% url 'easypr_admin:fetch-post' %}",
				type: "GET",
				data: {post_id:post_id, action:'send_to_media'},
				success: function(data){
					$("#id_media_contacts").html(data);
					$("#active_post_id").val(post_id);
					$("#select_media_contact").modal('show');
				},
				error: function(){
					alert('failed ');
				}
			})
		})
	</script>

	<script>
		$('body').on('click', '.publish', function(){
			var post_id = $(this).attr('post_id');
			$("#publish_post_id").val(post_id);
			$("#post_urls").modal('show');
		})

		$('body').on('click','#add_url_field', function(){
	        var newfield = document.createElement('div');
	        newfield.innerHTML = "<input type = 'text' name='post_url[]' class='form-control' placeholder = 'Enter media url. eg. http://vanguardngr.com/new-topic-here' /><br/>";
	        document.getElementById('id_post_urls').appendChild(newfield);
	    })
	</script>


	<script>
	// check if changes have been made to post title or body
		count = 0;
		$('body').on('keypress', '#id_post_title, #id_post_body', function(){
			count++;
			$("#is_edited").val(count);
			if (parseInt(count) > 0){
				$("#is_edited").val("edited");
			}	
		})

		$("#id_discard_changes").on('click', function(){
			if ($("#is_edited").val() == "edited"){
				return confirm("Changes you made will be lost. Are you sure you want to close this page?");
			}
		})

		$("#id_save_changes").on('click', function(){
			if ($("#is_edited").val() == "edited"){
				return confirm("Save changes to this post?");
			}
		})

		$('body').on('click', '#id_select_all', function(){
			$("#id_select_all").is(':checked') ? $(".media_contact").attr('checked', true) : $(".media_contact").attr('checked', false);
		})


		$('body').on('click', '.reject-post', function(){
			var post_id = $(this).attr('post_id');
			$("#reject_post_id").val(post_id);
			$("#rejection_reason").modal('show');
		})

		
	</script>
{% endblock inline_scripts %}